//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldGroupProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int menuID { get; set; }
        public string size { get; set; }
        public string starch { get; set; }
        public string protein { get; set; }
        public string price { get; set; }
        public string userId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
