//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldGroupProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string size { get; set; }
        public string starch { get; set; }
        public string protein { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
